- name: Generate and Upload CSV Report
  hosts: localhost
  gather_facts: yes

  vars:
    artifactory_url: "http://98.84.183.28:8082"
    artifactory_repo: "connectivity-reports"

  tasks:

    - name: Verify token injection
      debug:
        msg: "Token Length={{ lookup('env','JFROG_ACCESS_TOKEN') | length }}"

    - name: Upload CSV to JFrog Artifactory
      uri:
        url: "{{ artifactory_url }}/artifactory/{{ artifactory_repo }}/connectivity_report_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.csv"
        method: PUT
        headers:
          Authorization: "Bearer {{ lookup('env','JFROG_ACCESS_TOKEN') }}"
        src: /home/ubuntu/connectivity_report.csv
        status_code:
          - 200
          - 201
      register: upload_result