---

. name: AWX Connectivity Test
  hosts: all
  gather_facts: no

  tasks:

  . name: Ping target host
    ping:

  . name: Get hostname
    command: hostname
    register: hostname_out

  . name: Show hostname
    debug:
    var: hostname_out.stdout
