---
- hosts: all
  gather_facts: no

  tasks:

    - name: Ping host
      ping:
      register: ping_result
      ignore_errors: yes
      ignore_unreachable: yes

    - name: Print CSV record
      debug:
        msg: "{{ inventory_hostname }},SUCCESS,N/A"
      when: ping_result is succeeded

    - name: Print CSV record for failure
      debug:
        msg: "{{ inventory_hostname }},FAILED,{{ ping_result.msg | default('Unknown Error') }}"
      when: ping_result is failed