---

* name: AWX Connectivity Test
  hosts: all
  gather_facts: no

  tasks:

  * name: Ping target host
    ping:

  * name: Get hostname
    command: hostname
    register: host_name

  * name: Display hostname
    debug:
    var: host_name.stdout
